# Generated by Django 2.0.13 on 2020-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='hong kil dong', max_length=30),
            preserve_default=False,
        ),
    ]
