# Generated by Django 2.0.13 on 2020-01-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200115_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_no1',
            field=models.CharField(default='010', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='phone_no2',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='phone_no3',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
    ]
